### ISSUE TITLE
Suggestion: add gitter chat so that people can collaborate and ask questions

### ISSUE THREAD

**Issue by szarouski** [sourcejs/Source#120]
Hi, gitter is quite a great tool which allows people with github account to chat and ask questions specific to current repository. Couple of examples: https://gitter.im/babel/babel, https://gitter.im/tj/co, https://gitter.im/iojs/io.js.

It is very easy to add gitter badge to sourcejs repo, go to https://gitter.im/, sign in with github account and install github application. Click create a room at the bottor left corner and select sourcejs/Source repo. Gitter will send you a pull request which contains a link and a badge to chat room for sourcejs repo.

I think it is quite a good solution as there will be more people who can help in chat rooms, than people who watch repo on git. 

I'm not 'selling' you gitter, I just have a few questions and I feel that kind of workflow would work well for everybody. :)

**Comment by operatino** [comment]
Hi, you got a nice point here. 

Actually we already have Gitter chat setup, and we had a badge in README as well - https://gitter.im/sourcejs/Source.

We removed the badge because of low activity on Gitter, and poor popularity of it among developers. For questions it's better to use issues, since it's easier to navigate through them, but feel free to use Gitter as well. 

You also could always ping me on twitter on @operatino and @sourcejs account, so I could answer your questions sooner.

**Comment by operatino** [comment]
Added a badge again, also to other project repos. Hope it will be used more than last time.
