### ISSUE TITLE
Make core middlewares configurable (for e.g. custom Markdown tags)

### ISSUE THREAD

**Issue by mik01aj** [sourcejs/Source#155]
Originally suggested in https://github.com/szarouski/sourcejs-react/issues/5#issuecomment-109986079

I'm not sure whether there would be any more use cases for that, aside the Markdown custom tags... Or maybe we could even narrow this to only handling the code in `example` in some special way.

**Comment by operatino** [comment]
From Gitter:

How do you think, If I'll add another type of plugin entry file that will be executed during markdown processing, will it be enough for you? I can do same as with middleware plugins, including plugins in specified step of the page rendering.

In plugins we have special convention for that:

```
core
    middleware/index.js - loaded in process of page rendering flow
    markdown/index.js - could follow the same logic, and be required during MD processing
```

**Comment by szarouski** [comment]
@operatino  :+1:

**Comment by mik01aj** [comment]
@operatino The pic is so poor quality you don't see anything! :P

![screenshot 2015-06-18 16 49 17](https://cloud.githubusercontent.com/assets/3027415/8300967/9f6173b0-198a-11e5-9d20-4a3dc4536f7f.png)

**Comment by operatino** [comment]
I made markdown processing more configurable so it's now possible to define custom language renderers or re-define some part (or whole) renderer. I decided that this is the safest way, which also will allow to do only small changes, instead of overriding whole markdown renderer.

Check this example plugin and it's install instructions https://github.com/sourcejs/sourcejs-example-md-extension. @szarouski, @mik01aj, could you verify it?

Latest changes are available in 0.5.4-dev branch.

**Comment by mik01aj** [comment]
@operatino I just downloaded and installed your example plugin and it works! :) I will now work on extending it.

**Comment by mik01aj** [comment]
I just published a new plugin for React. It is based on your example.

https://github.com/mik01aj/sourcejs-md-react

**Comment by operatino** [comment]
@mik01aj Great thing! Do you have plans to merge it with @szarouski plugin?

I will close this issue, since it's solved and working.

**Comment by szarouski** [comment]
@operatino I think our plugins should be kept separate. They are different - one allows to run specs as jsx, another to process jsx from md files. I think both solutions are good and will find their users.

**Comment by mik01aj** [comment]
@operatino I think that this API could be refined. I had to put 4 declarations in `options.js`, and every user of the library will have to do it too... Furthermore, my solution is not perfect, as I keep the init code in some global vars, and it means that if you omit the `jsx-init-server` or any other `init` section, the SourceJS server will use whatever was used in the last displayed page. I thought that maybe I'd use a `languageRenderer` to reset these variables each time a new Markdown file is loaded, but didn't implement it yet.

I think that adding the custom parsers for MD code blocks should be the plugin's job, not the user's, just like adding new menu items.

**Comment by operatino** [comment]
@mik01aj I agree that it's not perfect, but I didn't found any other clean and simple solutions. It may become a mess if I'll have many includes around the codebase, that will `require` some convention-driven plugin files.

Another way was to allow plugins changing the options during app init, but it may be very dangerous, since could lead to unpredictable behaviour.

I wanted to keep clean customisation flow, when user knows what is overridden and could have control over that. Since you configure and install plugin only once (for the current instance, which is commonly used by whole team), it supposed to be not a big problem. 

You can also do this kind of configuration, to minimize options:

module.exports = {
    core: {
        processMd: {
            languageRenderers: (require('sourcejs-md-react')). languageRenderers()
        }
        // ...
    }
    // ...
};

`languageRenderers` are then extended (not rewritten) in the core module, so you don't override other renderers with different names.

**Comment by mik01aj** [comment]
There is a problem with this middleware. When I put a block like this in my spec:

    ```jsx-component-init-common
    ```

The middleware receives triple  ``` ` ``` instead of an empty string.

**Comment by operatino** [comment]
Most likely this is an issue with marked https://github.com/chjj/marked, the original dependency that renders Markdown into HTML. Could you please do a synthetic test with it?

**Comment by mik01aj** [comment]
Ok, just reported.

**Comment by operatino** [comment]
This is why I chose to control it from options, user define which renderers, from which plugins to use by himself in his own options. Plugins can't just override MD renderer without user's notice. Only the one which is set in options will be loaded.

**Comment by mik01aj** [comment]
@operatino, by "overrideing the `renderer.code` method" I meant overriding using your newly-added setting:

        processMd: {
            marked: {
                renderer: require('sourcejs-example-md-extension/custom-renderer')
            }
        }

Now if I override `renderer.code` there, do the `languageRenderers` stop working?

**Comment by operatino** [comment]
@mik01aj In case you override `renderer.code`, `languageRenderers` will stop working. `renderer.code` contains this special logic in core https://github.com/sourcejs/Source/blob/master/core/lib/processMd.js.
