### ISSUE TITLE
Recommended production workflow

### ISSUE THREAD

**Issue by issunboshi** [sourcejs/Source#161]
Hi,

I have built up a component library using Source and am now ready to start building up pages which use the components.

My ideal workflow would be to use the EJS templates directly within my production pages so that there is no duplication of components. I just want to check if there are any guidelines on how best to do this within Source? My current preference is to create another directory at the same level as user/specs to hold pages/templates and then include the EJS templates from user/specs directly in my templates.

I currently have this in place and it seems to work. I just want to check that I'm not using Source for something that it wasn't intended for and if there is a cleaner way to achieve this.

Any advice on this would be appreciated.

Thanks,

Cliff

**Comment by mik01aj** [comment]
I have my components in a separate npm module. My source documentation depends on that module, and whenever I need to require something, I use the `node_modules/my-frontend/...` path (and from js, I don't even need that). This way I can ship my components without the documentation, and thanks to `npm link` my documentation is always in sync with the components that I develop.

**Comment by operatino** [comment]
Hi @issunboshi,

To be honest, I hadn't even thought about this approach in building pages in SourceJS :) So unfortunately, there's no specific guide about that. 

But following your previous issue #160 with structure definition, your approach perfectly fits SourceJS workflow. Since the engine is quite scalable, you can play with own organazational process aligning it with specific use-cases.

We've been using Mustache and our own templating engine in my prev team, so it's totally up to you, which technology to use for building your examples. EJS is an out of the box tech, which allows to have some logic inside, but if on your main project you use other templating engines, then I would suggest using them.

If you're focusing only on HTML prototypes, then EJS will be the best choice to use within the SourceJS. 

BTW, I would be really thankful, if you could describe your approach in some short blog post or in our how-to's repo https://github.com/sourcejs/blog-howto.

**Comment by operatino** [comment]
@mik01aj Do you only include your node components to other pages, or these components contains their own documentation inside?

```
node_modules
    component
        info.json
        index.src.html
```

We're following this approach with bower_components, where each item has it's own SourceJS compatible documentation.

**Comment by mik01aj** [comment]
I have only `info.json` and `readme.md` (and the thumbnail) in my spec folders. The readme contains the documentation and all the necessary code to run the examples. And the frontend project contains only components and their unit tests (we don't have many, it's damn hard to write good unit tests for frontend).

**Comment by operatino** [comment]
@mik01aj Didn't you tried to keep documentation right in node modules? In this case you won't need to maintain separate specs.

**Comment by mik01aj** [comment]
This seems like a good idea, I'll try to change this structure when I have time.

**Comment by operatino** [comment]
I'm asking, because in 0.5.4 I excluded `node_modules` from indexing (for navigation) by default. But it's configurable :)

**Comment by issunboshi** [comment]
@operatino Thanks for getting back to me. I'll refine my current system and then post a blog/add something to the how-to's repo.
