### ISSUE TITLE
Ability to choose the CSS markup style

### ISSUE THREAD

**Issue by custa1200** [sourcejs/Source#162]
While I used to be a massive fan of using underscores (_) to separate words in CSS classes with the advent of many libraries like Bootstrap and Foundation I changed to use hyphens (-) and am now more comfortable using it. Is there some design decision that stops source from taking the lead from other libraries/systems? Is there some way this could be configurable?

**Comment by operatino** [comment]
Hi,

Somewhere after 0.6.0, we plan to make SourceJS UI very configurable and easy to style, which will allow to easily override all the markup and styles, keeping only functional hooks,

Since currently UI doesn't have much markup at all, and for defining specs you basically need only few CSS classes (`source_section`, `source_example`), it's not that big of a problem. It's partially possible to override some functional classes for JS features from the configuration, but it's not yet stable and reliable.
