### ISSUE TITLE
Provide LESS compiling also on /user level styles

### ISSUE THREAD

**Issue by mistermark** [sourcejs/Source#166]
The core of SourceJS is using LESS stylesheets for the styles. It would be good if the user customisation can also use these same format to write styles.

Currently it only takes CSS files, and not LESS files.

**Comment by operatino** [comment]
It doesn't really matter which preprocessor you use on the user customisation level, since it's just an extension on top. We should not provide any opinion on that out of the box. Besides, LESS compilation set-up is a question of 10 min job.

I'm not sure how the SourceJS UI styling topic will evolve in nearest updates, we definitely have some difficulties right now. That means that I also can't be sure that we will be still using LESS.

But it could be a useful idea to allow changing the LESS variables from `user` configuration folder. And most likely using an abstractions on top with JSON.

**Comment by mistermark** [comment]
Whatever flavour of css precompiling SourceJS is gonna use, I'd like to be able to use the same processor in the `user` folder. If that's going to be possible in the future, I'll be a happy ~~camper~~ coder.

**Comment by operatino** [comment]
My position is to keep `user` folder as clean as possible. So instead of populating starting `user` template with opinionated tech and build scripts I would go for an additional set of instructions (or how-to article) instead.

As soon as I will set-up project blog, I will schedule a blog post about theming SourceJS, where I will also attach example build script.

All the articles in the blog will be open for contribution via PR's, so your input will be highly welcome. Would be really great if you could draft the how-to guide about theming, so I could have more time on other requested improvements instead.

**Comment by ndelangen** [comment]
I think it would be interesting to try and expose injecting less files into sourcejs Core for plugins. But not so much for user code.

If we wanted to provide some sort of opinionated stack for building things on we would do so as a plugin. [sourcejs-react-styleguidist](https://github.com/sourcejs/sourcejs-react-styleguidist) is an example of that.

I agree with @operatino that user-code and sourcejs-code should be independent. 

When installed as a npm dependency -which will become the preferred method in 0.6.0 and the only method in 0.7.0- user-code and sourcejs-code are completely separated.

Can we close this?

**Comment by operatino** [comment]
As we decided to ship sourcejs only as already built app, the user won't have the tools installed to process LESS or other parts the same way SourceJS core does. So the only way for branding the UI will be using own styles build system, or plugins like https://www.npmjs.com/package/sourcejs-less.
