### ISSUE TITLE
includeFiles doesn't seem to work 

### ISSUE THREAD

**Issue by adesca** [sourcejs/Source#238]
In a test [readme](https://github.com/sourcejs/Source/files/350888/readme.txt) file I'm trying to include both a markdown file, that only has html, and a .partial file that contains the same content as the markdown files. These files are attached as [table.txt](https://github.com/sourcejs/Source/files/350889/table.txt). 

When  a markdown include and a file include are both in the same readme, the EJS parser seems to have trouble and doesn't include either file. When only Markdown files are included the files are included fine. When I attempt to include any file with a globstar, then the files are not included.

**Comment by ndelangen** [comment]
Thanks, I'll see what I can find out.

**Comment by operatino** [comment]
Hi,

I've done few tests in `0.6.0-dev` branch, and looks like both EJS helpers are working fine (`includeFiles` and `includeMD`). Please make sure that if you use `includeMD`, that you're specifically call `*.md` files, otherwise use `includeFiles`, for situations when you need to import files with markup. Here's the documentation for those methods https://sourcejs.com/docs/spec-helpers/.

Glob should also work, I've tested in this setup:

```example
<%- includeFiles('./partial*.txt'); %>
```

Where next to main `readme.md` file which includes this import, I have `partial1.txt` and `partial2.txt`.

When you see that something is not working in the development mode, please check the console for errors, that may lead you to the solution.
