### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by XOP** [sourcejs/Source#95]
Similarly to any modern browser, this feature has been designed to make access to the most used documents more convenient.

Basic features:
- add / remove specs to / from "favourites" section
- placement of "favourites" is configurable; by default - most of the main page, reflected in toolbar
- "favourites" can serve in two modes - user-configured and automatic, which considers frequency of specs using
- presumably, 8 is the best limit for the "favourites" section

**Comment by operatino** [comment]
I like this idea, really useful for big teams and libraries.

Since SourceJS could be extended quite deeply with plugins, and this feature is mostly focused only on big libraries, it's better to create a separate plugin for that. As you can define back-end, front-end and middleware from plugin, you will have everything you need for this feature.
